name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Dependencies
      run: |
        sudo apt-get install graphviz libgraphviz-dev pkg-config
        pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
        git clone https://github.com/rx-modules/mapper.git
        rm example.jpeg || true
        rm example_labeled.jpeg || true
    - name: map
      run: |
        cp mapper/* .
        cp ./.github/workflows/mapper.sh ./
        ./mapper.sh || true
    - name: Commit report
      run: |
        git config --global user.name 'MapperWorkflow'
        git config --global user.email 'actions@github.com'
        git add ./\*.jpeg || true
        git commit -m "Automated report"
        git push 
